version: '3.8'
name: two-databases

services:
  localdb:
    image: postgres:15.1-alpine
    container_name: dbase-pg
    ports:
      - 5435:5432
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=taq-bot
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=taq-bot

  auxiliardb:
    image: postgres:15.1-alpine
    container_name: dbase-pg-tests
    ports:
      - 5436:5432
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=tests
      - POSTGRES_PASSWORD=tests
      - POSTGRES_DB=tests